### ISSUE TITLE
Styling and Linting guides

### ISSUE THREAD

**Issue by jwu910** [5-gwoap/adopt-a-family#5]
Need to agree on and set up .editorConfig file and any linter settings files. 

We should all be on the same page about code base formatting.

**Comment by phuchle** [comment]
My Suggestions for code:

- Indents: 2 spaces (set your editor for tab to soft indent 2 spaces so you dont have to spam spaces)
- Variables: declare one per statement.  lowerCamelCase for vars, funcs, descriptions.  UpperCamelCase for classes.  UPPERCASE_SNAKE for constants.
- Semicolons: yes

General:

- ES6 when possible.
- Use single quotes unless writing JSON or HTML.
- Create descriptive names for variables, conditionals, functions et al when sane.  It's ok if you use a letter for the iterator in a for loop.

**Comment by jwu910** [comment]
Single line variable declaration?

**Comment by rainrivas** [comment]
```node
var someThing = 'element',
  otherThing = 'choice2';

/// instead of 
var someThing = 'element', otherThing = 'choice2';
```

**Comment by jwu910** [comment]
i meant single declaration declaration... lol

```node
var variableOne = 1,
    variableTwo = 2;

// vs

var variableOne = 1;
var variableTwo = 2;
```

**Comment by phuchle** [comment]
I actually prefer this style the most, on reconsideration:

```javascript
var variableOne = 1;
var variableTwo = 2;
```

**Comment by rainrivas** [comment]
I prefer variable grouping when they're the same type and they are basic style of `var`
I believe every `const` and`let` should be it's own line
```node
var variableOne = 1,
    variableTwo = 2;

let x = 3;
let y = 4;

const SECRET_KEY = "secret";
const LOGIN_OPTIONS = { // ... login http props .. // };

**Comment by phuchle** [comment]
@rainrivas I can agree to that style.

**Comment by jwu910** [comment]
I thought let and const was supposed to replace the use of var in es6

But i"m cool with that. Grouping def yes. Some organization to variable declaration is always welcome.

**Comment by rainrivas** [comment]
@jwu910 `let` and `const` are alternatives to always using `var`
`let` is a block scoped variable that is meant for use in functions or as a temporary thing that we delete after it's use (it doesn't persist or get hoisted to global scope like `var` could
`const` is a constant that is protected so we no longer use things like `var CONST_TIMEOUT` since now we have the `const` type
`var` is still your standard go-to variable for all other basic things.
Full details: 
* [MDN - var](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var)
* [MDN - let](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let)
* [MDN - const](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const)

**Comment by jwu910** [comment]
Thanks for ref. ES6 is on my todo. =[

Makes sense
