### ISSUE TITLE
Footer Links have target _blank

### ISSUE THREAD

**Issue by rainrivas** [5-gwoap/adopt-a-family#54]
@phuchle saw in the footer links `target _blank` that opens up a security risk as detailed here: https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c

**Comment by phuchle** [comment]
oh lol I should have just done this!

The fix is to add: `rel="noopener noreferrer"` to links that have `target="_blank"`

**Comment by jwu910** [comment]
Thanks! Didn't know about that

On Oct 15, 2017 16:07, "Tyler (Phuc) Le" <notifications@github.com> wrote:

oh lol I should have just done this!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/5-gwoap/adopt-a-family/issues/54#issuecomment-336748776>,
or mute the thread

**Comment by jwu910** [comment]
@psyduc You wanna take care of this one?
